Repository WildCodeSchool/orleans-202109-php-project-cerha, pull requests merged in 2021-12, with the labels that each got.

#6 initialization css variable and bootstrap
  assets/app.js
  assets/styles/app.scss
  assets/styles/variables.scss
  composer.lock
  config/packages/twig.yaml
  package-lock.json
  package.json
  symfony.lock
  templates/base.html.twig
  templates/home/index.html.twig
  yarn.lock
Labels: Reviewed

#28 Us31 s01 page contact
  assets/images/logo-cerha.png
  assets/styles/app.scss
  src/Controller/ContactController.php
  templates/contact/index.html.twig
Labels: Reviewed

#30 add map
  assets/styles/contact.scss
  templates/contact/index.html.twig
  webpack.config.js
Labels: Reviewed

#29 Added a section "presentation of the enterprise" in the page "about"
  src/Controller/AboutController.php
  templates/about/index.html.twig
Labels: Reviewed

#32 S01US01 Navbar
  assets/images/favicon.png
  assets/images/logo-detoure.png
  assets/styles/app.scss
  assets/styles/navbar.scss
  templates/base.html.twig
  templates/items/_navbar.html.twig
Labels: Reviewed

#35 presentation of the enterprise is now responsive
  assets/styles/variables.scss
  templates/about/index.html.twig
Labels: Reviewed

#33 S01 us37 display services
  assets/images/services-company.jpg
  assets/images/services-particular.jpg
  assets/styles/app.scss
  assets/styles/services.scss
  assets/styles/variables.scss
  package-lock.json
  package.json
  src/Controller/ServiceController.php
  templates/services/_company-services.html.twig
  templates/services/_particular-services.html.twig
  templates/services/index.html.twig
  webpack.config.js
  yarn.lock
Labels: Reviewed

#39 S01US35-Mission-Section
  templates/about/index.html.twig
Labels: Reviewed

#44 fix links in navbar
  templates/items/_navbar.html.twig
Labels: Reviewed

#40 S01US02_Footer
  assets/images/Inosearch.png
  assets/images/QRCode.png
  assets/styles/app.scss
  assets/styles/footer.scss
  templates/base.html.twig
  templates/items/_footer.html.twig
Labels: Reviewed

#45 added goodnesses of the enterprise in the about page
  templates/about/index.html.twig
Labels: Reviewed

#41 S01 us04 display services cards homepage
  assets/images/company.jpg
  assets/images/particular.jpg
  assets/styles/home.scss
  templates/home/index.html.twig
  templates/items/_services-cards.html.twig
  webpack.config.js
Labels: Reviewed

#34 S01US36 team presentation
  assets/styles/about.scss
  assets/styles/variables.scss
  migrations/Version20211217010327.php
  src/Controller/AboutController.php
  src/DataFixtures/EmployeeFixtures.php
  src/Entity/Employee.php
  src/Repository/EmployeeRepository.php
  templates/about/index.html.twig
  webpack.config.js
Labels: Reviewed

#46 Dev -> Master
  assets/app.js
  assets/images/Inosearch.png
  assets/images/QRCode.png
  assets/images/company.jpg
  assets/images/favicon.png
  assets/images/logo-cerha.png
  assets/images/logo-detoure.png
  assets/images/particular.jpg
  assets/images/services-company.jpg
  assets/images/services-particular.jpg
  assets/styles/about.scss
  assets/styles/app.scss
  assets/styles/contact.scss
  assets/styles/footer.scss
  assets/styles/home.scss
  assets/styles/navbar.scss
  assets/styles/services.scss
  assets/styles/variables.scss
  composer.lock
  config/packages/twig.yaml
  migrations/Version20211217010327.php
  package-lock.json
  package.json
  src/Controller/AboutController.php
  src/Controller/ContactController.php
  src/Controller/ServiceController.php
  src/DataFixtures/EmployeeFixtures.php
  src/Entity/Employee.php
  src/Repository/EmployeeRepository.php
  symfony.lock
  templates/about/index.html.twig
  templates/base.html.twig
  templates/contact/index.html.twig
  templates/home/index.html.twig
  templates/items/_footer.html.twig
  templates/items/_navbar.html.twig
  templates/items/_services-cards.html.twig
  templates/services/_company-services.html.twig
  templates/services/_particular-services.html.twig
  templates/services/index.html.twig
  webpack.config.js
  yarn.lock
Labels: Reviewed

#43 Us33 s01 form contact
  assets/styles/contact.scss
  composer.json
  composer.lock
  config/packages/translation.yaml
  config/services.yaml
  src/Controller/ContactController.php
  src/Entity/Contact.php
  src/Form/ContactType.php
  src/Repository/.gitignore
  symfony.lock
  templates/contact/index.html.twig
  templates/contact/newEmail.html.twig
Labels: Reviewed

#47 Fix-contact
  assets/styles/contact.scss
  assets/styles/navbar.scss
  assets/styles/variables.scss
  templates/contact/index.html.twig
Labels: Reviewed

#42 S01US03_banner
  assets/images/banner.jpg
  assets/styles/banner.scss
  templates/home/index.html.twig
  templates/items/_banner.html.twig
  webpack.config.js
Labels: Reviewed

#48 fixed the banner not included
  templates/home/index.html.twig
Labels: Reviewed

#70 fix issues with cards onhome page, size, button, line height
  assets/styles/home.scss
  assets/styles/variables.scss
  templates/home/index.html.twig
  templates/items/_services-cards.html.twig
Labels: Reviewed

#69 fix issues on displayed cards, spacing, size
  assets/images/CV.svg
  assets/styles/services.scss
  assets/styles/variables.scss
  templates/items/_navbar.html.twig
  templates/services/_company-services.html.twig
  templates/services/_particular-services.html.twig
  templates/services/index.html.twig
Labels: Reviewed

#135 Fix about page style
  assets/styles/about.scss
  templates/about/index.html.twig
Labels: Reviewed

#136 S02US05-connexion
  assets/styles/login.scss
  config/packages/security.yaml
  migrations/Version20211220152645.php
  src/Controller/SecurityController.php
  src/DataFixtures/UserFixtures.php
  src/Entity/User.php
  src/Repository/UserRepository.php
  templates/items/_navbar.html.twig
  templates/login/index.html.twig
  webpack.config.js
Labels: Reviewed, Correction Done

#139 S02 us18 display hobbies
  assets/styles/profile.scss
  composer.json
  composer.lock
  migrations/Version20211221142231.php
  src/Controller/CandidatController.php
  src/DataFixtures/HobbyFixtures.php
  src/Entity/Hobby.php
  src/Repository/HobbyRepository.php
  symfony.lock
  templates/candidat/components/_hobbies.html.twig
  templates/candidat/index.html.twig
Labels: Change request, Reviewed

#141 fixed logos colors and put legal notice at the bottom
  assets/images/CERHA-logo-detoure.svg
  assets/images/QRCode.png
  assets/styles/footer.scss
  composer.lock
  templates/items/_footer.html.twig
  yarn.lock
Labels: Reviewed

#145 Fixes banner
  assets/styles/banner.scss
  templates/items/_banner.html.twig
Labels: Reviewed
