Repository WildCodeSchool/orleans-202109-php-project-cerha, pull requests merged in 2022-02, with the labels that each got.

#422 added a 401 response page
  templates/bundles/TwigBundle/Exception/error401.html.twig
Labels: Reviewed

#423 added a 404 page response
  templates/bundles/TwigBundle/Exception/error404.html.twig
Labels: Reviewed

#424 added a 500 response page
  templates/bundles/TwigBundle/Exception/error500.html.twig
Labels: Reviewed

#427 fix-referent
  templates/candidate/components/_experiences.html.twig
  templates/candidate/components/_formations.html.twig
Labels: Reviewed

#425 Fix date
  src/Entity/Experience.php
  src/Entity/Formation.php
  templates/candidate/components/_experiences.html.twig
  templates/candidate/components/_formations.html.twig
Labels: Reviewed

#426 fix-candidate-description
  templates/candidate/components/_experiences.html.twig
  templates/candidate/components/_formations.html.twig
Labels: Reviewed

#461 add assert
  composer.json
  src/Entity/Contact.php
Labels: Reviewed

#462 added margin and modified accessibility
  assets/styles/about.scss
  templates/about/index.html.twig
Labels: Reviewed

#463 add assert
  src/Entity/Candidate.php
Labels: Reviewed

#464 add text and images
  assets/images/business1.jpg
  assets/images/particullar.jpg
  templates/items/_services-cards.html.twig
Labels: Reviewed

#466 Fix target blank
  templates/admin_candidate/index.html.twig
  templates/registration/register.html.twig
Labels: Reviewed

#467 change languages title
  templates/candidate/components/_languages.html.twig
  templates/candidate/edit/languages.html.twig
Labels: Reviewed

#468 mooved style from pdf.scss to the head of base_pdf.html.twig
  assets/styles/pdf.scss
  templates/base_pdf.html.twig
  webpack.config.js
Labels: Reviewed, Fix

#469 fix-date-CV
  templates/admin_candidate/cvPdf.html.twig
Labels: Reviewed

#470 use vich to display employee pictures
  templates/about/index.html.twig
Labels: Reviewed, Fix

#471 erased flash message out of the base.html.twig file
  templates/contact/index.html.twig
  templates/registration/register.html.twig
  templates/reset_password/request.html.twig
  templates/reset_password/reset.html.twig
Labels: Reviewed, Fix

#472 fix-documents
  src/Entity/AdditionalDocument.php
  src/Entity/Candidate.php
  src/Form/CandidateExperienceType.php
  src/Form/CandidateFormationsType.php
  templates/candidate/components/_documents.html.twig
  templates/candidate/edit/edit.document.html.twig
Labels: Reviewed

#475 Fix autres
  src/Entity/User.php
  src/Form/UserCompanyType.php
  templates/candidate/edit/edit.contactDetails.html.twig
  templates/registration/register.html.twig
Labels: Reviewed

#474 Fixes admin candidate
  templates/admin_candidate/_delete_form.html.twig
  templates/admin_candidate/index.html.twig
  templates/admin_candidate/show.html.twig
  templates/admin_company/_delete_form.html.twig
  templates/admin_company/index.html.twig
  templates/admin_company/show.html.twig
  templates/admin_employee/_delete_form.html.twig
  templates/admin_employee/_form.html.twig
  templates/admin_employee/edit.html.twig
  templates/admin_employee/index.html.twig
  templates/admin_service/_delete_form.html.twig
  templates/admin_service/_form.html.twig
  templates/admin_service/index.html.twig
  templates/admin_service_category/_delete_form.html.twig
  templates/admin_service_category/_form.html.twig
  templates/admin_service_category/index.html.twig
Labels: Reviewed

#476 deleted services into migration
  migrations/Version20220130103648.php
Labels: Reviewed

#477 dev to master
  assets/images/business1.jpg
  assets/images/particullar.jpg
  assets/styles/about.scss
  assets/styles/pdf.scss
  composer.json
  migrations/Version20220130103648.php
  src/Entity/AdditionalDocument.php
  src/Entity/Candidate.php
  src/Entity/Contact.php
  src/Entity/Experience.php
  src/Entity/Formation.php
  src/Entity/User.php
  src/Form/CandidateExperienceType.php
  src/Form/CandidateFormationsType.php
  src/Form/UserCompanyType.php
  templates/about/index.html.twig
  templates/admin_candidate/_delete_form.html.twig
  templates/admin_candidate/cvPdf.html.twig
  templates/admin_candidate/index.html.twig
  templates/admin_candidate/show.html.twig
  templates/admin_company/_delete_form.html.twig
  templates/admin_company/index.html.twig
  templates/admin_company/show.html.twig
  templates/admin_employee/_delete_form.html.twig
  templates/admin_employee/_form.html.twig
  templates/admin_employee/edit.html.twig
  templates/admin_employee/index.html.twig
  templates/admin_service/_delete_form.html.twig
  templates/admin_service/_form.html.twig
  templates/admin_service/index.html.twig
  templates/admin_service_category/_delete_form.html.twig
  templates/admin_service_category/_form.html.twig
  templates/admin_service_category/index.html.twig
  templates/base_pdf.html.twig
  templates/bundles/TwigBundle/Exception/error401.html.twig
  templates/bundles/TwigBundle/Exception/error404.html.twig
  templates/bundles/TwigBundle/Exception/error500.html.twig
  templates/candidate/components/_documents.html.twig
  templates/candidate/components/_experiences.html.twig
  templates/candidate/components/_formations.html.twig
  templates/candidate/components/_languages.html.twig
  templates/candidate/edit/edit.contactDetails.html.twig
  templates/candidate/edit/edit.document.html.twig
  templates/candidate/edit/languages.html.twig
  templates/contact/index.html.twig
  templates/items/_services-cards.html.twig
  templates/registration/register.html.twig
  templates/reset_password/request.html.twig
  templates/reset_password/reset.html.twig
  webpack.config.js
Labels: Reviewed

#478 fix-assert-group-company
  src/Entity/Company.php
  src/Form/CompanyContactType.php
  src/Form/CompanyDetailsType.php
Labels: Reviewed

#480 change softskill title
  src/Form/SoftSkillsType.php
  templates/candidate/components/_soft-skills.html.twig
  templates/candidate/edit/sofskills.html.twig
Labels: Reviewed

#483 Fix company properties
  migrations/Version20220130103648.php
  src/DataFixtures/CompanyFixtures.php
  src/Entity/Company.php
  src/Form/CompanyDetailsType.php
  templates/company/components/_formCompanyDetails.html.twig
Labels: Reviewed

#484 fix-document-name
  src/Form/DocumentType.php
Labels: Reviewed

#485 added help needed field
  migrations/Version20220207172733.php
  src/Entity/Candidate.php
  src/Form/ComplementaryQuestionType.php
  templates/admin_service/index.html.twig
  templates/candidate/components/_complementary-questions.html.twig
  templates/candidate/edit/complementary-questions.html.twig
Labels: Reviewed

#486 Dev to master
  migrations/Version20220130103648.php
  migrations/Version20220207172733.php
  src/DataFixtures/CompanyFixtures.php
  src/Entity/Candidate.php
  src/Entity/Company.php
  src/Form/CompanyContactType.php
  src/Form/CompanyDetailsType.php
  src/Form/ComplementaryQuestionType.php
  src/Form/DocumentType.php
  src/Form/SoftSkillsType.php
  templates/admin_service/index.html.twig
  templates/candidate/components/_complementary-questions.html.twig
  templates/candidate/components/_soft-skills.html.twig
  templates/candidate/edit/complementary-questions.html.twig
  templates/candidate/edit/sofskills.html.twig
  templates/company/components/_formCompanyDetails.html.twig
Labels: Reviewed

#479 Fix forms style candidate
  assets/app.js
  assets/experiences.js
  assets/formations.js
  assets/hobbies.js
  assets/images/banner.jpg
  assets/languages.js
  assets/skills.js
  assets/softskills.js
  assets/styles/forms.scss
  assets/styles/variables.scss
  src/Controller/CandidateController.php
  templates/candidate/components/_skills.html.twig
  templates/candidate/edit/edit.contactDetails.html.twig
  templates/candidate/edit/edit.document.html.twig
  templates/candidate/edit/edit.experience.html.twig
  templates/candidate/edit/edit.formation.html.twig
  templates/candidate/edit/edit.skill.html.twig
  templates/candidate/edit/hobbies.html.twig
  templates/candidate/edit/languages.html.twig
  templates/candidate/edit/sofskills.html.twig
  webpack.config.js
Labels: Reviewed, Correction Done, Conflict

#487 Fix legal notice
  templates/legal-terms/legal-notice.html.twig
Labels: Reviewed

#482 added images and text
  assets/images/pexels-cottonbro-3584969.jpg
  assets/images/pexels-fauxels-3183156.jpg
  assets/images/teamwork-g834912e52_640.jpg
  src/DataFixtures/EmployeeFixtures.php
  src/DataFixtures/kevin.jpg
  src/DataFixtures/lionel.jpg
  src/DataFixtures/placeholder.png
  templates/about/index.html.twig
Labels: Reviewed, Fix, Correction Done

#488 changed label job title
  src/Form/CompanyContactType.php
Labels: Reviewed

#489 add condition for company
  templates/items/_navbar.html.twig
Labels: Reviewed

#490 fix-assert
  src/Entity/Candidate.php
  src/Entity/Company.php
  src/Entity/Experience.php
  src/Entity/Formation.php
Labels: Reviewed

#493 Fix cascade
  assets/images/banner-company.jpg
  assets/images/banner-particular.jpg
  assets/images/services-company.jpg
  assets/images/services-particular.jpg
  src/Entity/Company.php
  src/Entity/User.php
  templates/services/_company-services.html.twig
  templates/services/_particular-services.html.twig
Labels: Reviewed

#494 dev to master
  assets/app.js
  assets/experiences.js
  assets/formations.js
  assets/hobbies.js
  assets/images/banner-company.jpg
  assets/images/banner-particular.jpg
  assets/images/banner.jpg
  assets/images/pexels-cottonbro-3584969.jpg
  assets/images/pexels-fauxels-3183156.jpg
  assets/images/services-company.jpg
  assets/images/services-particular.jpg
  assets/images/teamwork-g834912e52_640.jpg
  assets/languages.js
  assets/skills.js
  assets/softskills.js
  assets/styles/forms.scss
  assets/styles/login.scss
  assets/styles/services.scss
  assets/styles/variables.scss
  src/Controller/CandidateController.php
  src/DataFixtures/EmployeeFixtures.php
  src/DataFixtures/kevin.jpg
  src/DataFixtures/lionel.jpg
  src/DataFixtures/placeholder.png
  src/Entity/Candidate.php
  src/Entity/Company.php
  src/Entity/Experience.php
  src/Entity/Formation.php
  src/Entity/User.php
  src/Form/CompanyContactType.php
  templates/about/index.html.twig
  templates/candidate/components/_skills.html.twig
  templates/candidate/edit/edit.contactDetails.html.twig
  templates/candidate/edit/edit.document.html.twig
  templates/candidate/edit/edit.experience.html.twig
  templates/candidate/edit/edit.formation.html.twig
  templates/candidate/edit/edit.skill.html.twig
  templates/candidate/edit/hobbies.html.twig
  templates/candidate/edit/languages.html.twig
  templates/candidate/edit/sofskills.html.twig
  templates/items/_navbar.html.twig
  templates/legal-terms/legal-notice.html.twig
  templates/login/index.html.twig
  templates/registration/register.html.twig
  templates/reset_password/check_email.html.twig
  templates/services/_company-services.html.twig
  templates/services/_particular-services.html.twig
  webpack.config.js
Labels: Reviewed

#495 assert
  src/Entity/Candidate.php
  templates/candidate/edit/complementary-questions.html.twig
  templates/candidate/edit/sofskills.html.twig
Labels: Reviewed
