Repository WildCodeSchool/orleans-202109-php-project-cerha, pull requests merged in 2022-01, with the labels that each got.

#151 change selector svg and color
  assets/styles/services.scss
  templates/services/_company-services.html.twig
Labels: Reviewed

#147 S02 us16 fix relation candidat sofskills
  migrations/Version20211227093320.php
  migrations/Version20211227094236.php
  src/Controller/CandidatController.php
  src/DataFixtures/CandidatFixtures.php
  src/DataFixtures/SoftSkillFixtures.php
  src/DataFixtures/UserFixtures.php
  src/Entity/Candidat.php
  src/Entity/SoftSkill.php
  src/Entity/User.php
  templates/candidat/components/_soft-skills.html.twig
  templates/items/_navbar.html.twig
Labels: Reviewed

#157 fix - profil - candidat
  templates/candidat/components/_contactDetails.html.twig
Labels: Reviewed

#149 S02 us09 company infos
  assets/styles/companyProfile.scss
  migrations/Version20211230141213.php
  src/Controller/CompanyController.php
  src/DataFixtures/CompanyFixtures.php
  src/Entity/Company.php
  src/Repository/CompanyRepository.php
  templates/company/components/_companyDetails.html.twig
  templates/company/index.html.twig
  webpack.config.js
Labels: Reviewed, Correction Done

#152 S02 us18 fix relation candidat hobby
  migrations/Version20211230193451.php
  src/Controller/CandidatController.php
  src/DataFixtures/HobbyFixtures.php
  src/Entity/Candidat.php
  src/Entity/Hobby.php
  templates/candidat/components/_hobbies.html.twig
Labels: Reviewed

#159 fixed banner width
  assets/styles/banner.scss
Labels: Reviewed

#158 Skills
  migrations/Version20220103125013.php
  src/DataFixtures/SectorFixtures.php
  src/DataFixtures/SkillFixtures.php
  src/Entity/Candidat.php
  src/Entity/Sector.php
  src/Entity/Skill.php
  src/Repository/SectorRepository.php
  src/Repository/SkillRepository.php
  templates/candidat/components/_skills.html.twig
  templates/candidat/index.html.twig
Labels: Reviewed, Correction Done

#161 S02 us19 complementary questions
  assets/styles/profile.scss
  composer.json
  composer.lock
  migrations/Version20211230201512.php
  src/DataFixtures/CandidatFixtures.php
  src/Entity/Candidat.php
  templates/candidat/components/_complementary-questions.html.twig
  templates/candidat/index.html.twig
Labels: Reviewed, Correction Done, Conflict

#165 S02US10 company contact
  assets/styles/companyProfile.scss
  migrations/Version20220104163322.php
  src/DataFixtures/CompanyFixtures.php
  src/DataFixtures/UserFixtures.php
  src/Entity/Company.php
  src/Entity/User.php
  templates/company/components/_companyContact.html.twig
  templates/company/index.html.twig
Labels: Reviewed

#166 fix-user-candidat
  src/DataFixtures/CandidatFixtures.php
  src/DataFixtures/HobbyFixtures.php
  src/DataFixtures/SkillFixtures.php
  src/DataFixtures/SoftSkillFixtures.php
  src/DataFixtures/UserFixtures.php
Labels: Reviewed, Correction Done

#167 added networks to company profile
  assets/styles/companyProfile.scss
  migrations/Version20220105092117.php
  src/DataFixtures/CompanyFixtures.php
  src/Entity/Company.php
  templates/company/components/_companyDetails.html.twig
Labels: Reviewed, Fix, Correction Done

#163 Us15 1 s02 candidat experiences
  migrations/Version20220104092214.php
  src/DataFixtures/ExperienceFixtures.php
  src/Entity/Candidat.php
  src/Entity/Experience.php
  src/Repository/ExperienceRepository.php
  templates/candidat/components/_experiences.html.twig
  templates/candidat/index.html.twig
Labels: Reviewed, Correction Done, Conflict

#170 US12-2-S02-edit-candidat
  src/Controller/CandidatController.php
  src/Entity/Candidat.php
  src/Form/ContactDetailsType.php
  templates/base.html.twig
  templates/candidat/components/_contactDetails.html.twig
  templates/candidat/edit/edit.contactDetails.html.twig
Labels: Reviewed

#172 Dev to master
  assets/styles/companyProfile.scss
  assets/styles/profile.scss
  composer.json
  composer.lock
  docker-entry.sh
  migrations/Version20211230201512.php
  migrations/Version20220103125013.php
  migrations/Version20220104074012.php
  migrations/Version20220104092214.php
  migrations/Version20220104163322.php
  migrations/Version20220105092117.php
  src/Controller/CandidatController.php
  src/DataFixtures/CandidatFixtures.php
  src/DataFixtures/CompanyFixtures.php
  src/DataFixtures/ExperienceFixtures.php
  src/DataFixtures/FormationFixtures.php
  src/DataFixtures/FormationLevelFixtures.php
  src/DataFixtures/HobbyFixtures.php
  src/DataFixtures/SectorFixtures.php
  src/DataFixtures/SkillFixtures.php
  src/DataFixtures/SoftSkillFixtures.php
  src/DataFixtures/UserFixtures.php
  src/Entity/Candidat.php
  src/Entity/Company.php
  src/Entity/Experience.php
  src/Entity/Formation.php
  src/Entity/FormationLevel.php
  src/Entity/Sector.php
  src/Entity/Skill.php
  src/Entity/User.php
  src/Form/ContactDetailsType.php
  src/Repository/ExperienceRepository.php
  src/Repository/FormationLevelRepository.php
  src/Repository/FormationRepository.php
  src/Repository/SectorRepository.php
  src/Repository/SkillRepository.php
  templates/base.html.twig
  templates/candidat/components/_complementary-questions.html.twig
  templates/candidat/components/_contactDetails.html.twig
  templates/candidat/components/_experiences.html.twig
  templates/candidat/components/_formations.html.twig
  templates/candidat/components/_skills.html.twig
  templates/candidat/edit/edit.contactDetails.html.twig
  templates/candidat/index.html.twig
  templates/company/components/_companyContact.html.twig
  templates/company/components/_companyDetails.html.twig
  templates/company/index.html.twig
Labels: Reviewed

#169 S02US07-Incription
  .env
  assets/styles/app.scss
  composer.json
  composer.lock
  config/bundles.php
  migrations/Version20220104131546.php
  src/Controller/RegistrationController.php
  src/Entity/User.php
  src/Form/RegistrationFormType.php
  src/Security/EmailVerifier.php
  symfony.lock
  templates/base.html.twig
  templates/login/index.html.twig
  templates/registration/confirmation_email.html.twig
  templates/registration/register.html.twig
Labels: Reviewed

#173 S02 us29 edit company contact
  assets/styles/editCompany.scss
  src/Controller/CompanyController.php
  src/Entity/Company.php
  src/Form/CompanyContactType.php
  src/Form/UserCompanyType.php
  templates/company/components/_companyContact.html.twig
  templates/company/components/_formCompanyContact.html.twig
  templates/company/editCompanyContact.html.twig
  webpack.config.js
Labels: Reviewed

#171 US12-S02-Edit-User-candidat
  migrations/Version20220106150034.php
  src/Entity/Candidat.php
  src/Entity/User.php
  src/Form/ContactDetailsType.php
  src/Form/UserCandidateType.php
  templates/candidat/components/_contactDetails.html.twig
  templates/candidat/edit/edit.contactDetails.html.twig
Labels: Reviewed, Correction Done

#175 Fix contact
  assets/styles/contact.scss
  templates/contact/index.html.twig
  templates/contact/newEmail.html.twig
Labels: Reviewed

#177 Fixed phone number is a string now
  src/Entity/User.php
  src/Form/RegistrationFormType.php
Labels: Reviewed

#189 Fix candidat style
  assets/app.js
  assets/styles/profile.scss
  templates/candidat/components/_contactDetails.html.twig
Labels: Reviewed

#191 Server should not be broken anymore
  composer.json
  composer.lock
  symfony.lock
Labels: Reviewed

#188 S02 us28 edit company details
  src/Controller/CompanyController.php
  src/Entity/Company.php
  src/Form/CompanyDetailsType.php
  templates/company/components/_companyDetails.html.twig
  templates/company/components/_formCompanyDetails.html.twig
  templates/company/editCompanyDetails.html.twig
Labels: Reviewed, Correction Done

#190 Us13 s02 edit skill
  package.json
  src/Controller/CandidatController.php
  src/Form/CandidateSkillsType.php
  src/Form/SkillType.php
  templates/candidat/components/_skills.html.twig
  templates/candidat/edit/edit.skill.html.twig
  templates/contact/newEmail.html.twig
  yarn.lock
Labels: Reviewed

#164 S02 us17 display languages candidat
  assets/styles/profile.scss
  composer.json
  composer.lock
  migrations/Version20220103151523.php
  src/Controller/CandidatController.php
  src/DataFixtures/CandidatLanguageFixtures.php
  src/Entity/Candidat.php
  src/Entity/CandidatLanguage.php
  src/Repository/CandidatLanguageRepository.php
  symfony.lock
  templates/candidat/components/_languages.html.twig
  templates/candidat/index.html.twig
Labels: Reviewed, Correction Done, Conflict

#195 S02 us24 create form for softskills bis
  assets/app.js
  assets/images/trash.svg
  assets/styles/forms.scss
  package-lock.json
  src/Controller/CandidatController.php
  src/DataFixtures/SoftSkillFixtures.php
  src/Entity/Candidat.php
  src/Entity/SoftSkill.php
  src/Form/SoftSkillType.php
  src/Form/SoftSkillsType.php
  templates/candidat/components/_soft-skills.html.twig
  templates/candidat/edit/sofskills.html.twig
  webpack.config.js
  yarn.lock
Labels: Reviewed

#196 S03 US30 need, edit and fixtures
  migrations/Version20220111102244.php
  src/Controller/CompanyController.php
  src/DataFixtures/CompanyFixtures.php
  src/Entity/Company.php
  src/Form/CompanyNeedType.php
  templates/company/components/_companyNeed.html.twig
  templates/company/components/_formCompanyNeed.html.twig
  templates/company/editCompanyNeed.html.twig
  templates/company/index.html.twig
Labels: Reviewed

#199 stylized delete button
  src/Controller/AdminCandidateController.php
  templates/admin_candidate/_delete_form.html.twig
Labels: Reviewed

#202 Us14 s03 edit formation
  assets/app.js
  assets/styles/forms.scss
  assets/styles/profile.scss
  composer.lock
  migrations/Version20220111092347.php
  src/Controller/CandidatController.php
  src/Entity/Candidat.php
  src/Entity/Formation.php
  src/Form/CandidateFormationsType.php
  src/Form/FormationType.php
  templates/candidat/components/_formations.html.twig
  templates/candidat/edit/edit.contactDetails.html.twig
  templates/candidat/edit/edit.formation.html.twig
  templates/candidat/index.html.twig
Labels: Reviewed, Correction Done

#217 US15-S03-EDIT-EXPERIENCES
  assets/app.js
  assets/styles/forms.scss
  assets/styles/profile.scss
  assets/styles/variables.scss
  migrations/Version20220112100131.php
  src/Controller/CandidatController.php
  src/DataFixtures/ContratFixtures.php
  src/DataFixtures/ExperienceFixtures.php
  src/Entity/Contrat.php
  src/Entity/Experience.php
  src/Form/CandidateExperienceType.php
  src/Form/ExperienceType.php
  src/Repository/ContratRepository.php
  templates/candidat/components/_experiences.html.twig
  templates/candidat/edit/edit.contactDetails.html.twig
  templates/candidat/edit/edit.experience.html.twig
Labels: Reviewed, Review needed

#218 fix-style-card
  assets/app.js
  assets/styles/forms.scss
  assets/styles/profile.scss
  src/Form/CandidateSkillsType.php
  src/Form/SkillType.php
  templates/candidat/components/_contactDetails.html.twig
  templates/candidat/components/_skills.html.twig
  templates/candidat/edit/edit.contactDetails.html.twig
  templates/candidat/edit/edit.skill.html.twig
Labels: Reviewed, Correction Done

#203 S03 us27 create form for complementary questions
  src/Controller/CandidatController.php
  src/Entity/Candidat.php
  src/Form/ComplementaryQuestionType.php
  templates/candidat/components/_complementary-questions.html.twig
  templates/candidat/edit/complementary-questions.html.twig
Labels: Reviewed, Correction Done

#212 Us39 display companylist for admins
  config/packages/security.yaml
  src/Controller/AdminCompanyController.php
  src/Controller/CandidatController.php
  src/Form/CompanyType.php
  src/Form/ComplementaryQuestionType.php
  templates/admin_company/_delete_form.html.twig
  templates/admin_company/_form.html.twig
  templates/admin_company/index.html.twig
  templates/admin_company/show.html.twig
  templates/candidat/edit/complementary-questions.html.twig
Labels: Reviewed, Correction Done, Conflict

#207 S03 us25 create form for language bis
  assets/app.js
  assets/styles/forms.scss
  src/Controller/CandidatController.php
  src/Entity/Candidat.php
  src/Form/CandidateLanguageType.php
  src/Form/CandidateLanguagesType.php
  templates/candidat/components/_languages.html.twig
  templates/candidat/edit/languages.html.twig
Labels: Reviewed, Correction Done, Conflict

#223 fix-contact
  assets/styles/contact.scss
  templates/contact/index.html.twig
Labels: Reviewed

#221 US16-S03-additional-document
  composer.json
  composer.lock
  config/bundles.php
  config/packages/vich_uploader.yaml
  config/services.yaml
  migrations/Version20220112144117.php
  public/uploads/candidate/CV.pdf
  src/DataFixtures/CV.docx
  src/DataFixtures/CV.pdf
  src/DataFixtures/CandidatFixtures.php
  src/DataFixtures/DocumentFixtures.php
  src/Entity/AdditionalDocument.php
  src/Entity/Candidat.php
  src/Repository/AdditionalDocumentRepository.php
  symfony.lock
  templates/candidat/components/_SideMenuCandidate.html.twig
  templates/candidat/components/_documents.html.twig
  templates/candidat/index.html.twig
Labels: Reviewed, Correction Done

#226 fixed sidebar company to look like candidate
  templates/company/components/_SideMenuCompany.html.twig
  templates/company/index.html.twig
Labels: Reviewed, Fix

#228 add button to hobbies form
  assets/app.js
Labels: Reviewed

#229 Fix company style
  assets/styles/companyProfile.scss
  templates/company/components/_companyContact.html.twig
  templates/company/components/_companyDetails.html.twig
  templates/company/components/_companyNeed.html.twig
  templates/company/components/_formCompanyContact.html.twig
  templates/company/index.html.twig
Labels: Reviewed

#225 S03 US61 CV
  assets/styles/pdf.scss
  composer.json
  composer.lock
  src/Controller/AdminCandidateController.php
  symfony.lock
  templates/admin_candidate/cvPdf.html.twig
  templates/admin_candidate/index.html.twig
  templates/base_pdf.html.twig
  webpack.config.js
Labels: Reviewed

#233 changed all title of the site to be more logic
  templates/admin_company/index.html.twig
  templates/admin_company/show.html.twig
  templates/candidat/edit/complementary-questions.html.twig
  templates/candidat/edit/edit.contactDetails.html.twig
  templates/candidat/edit/edit.experience.html.twig
  templates/candidat/edit/edit.formation.html.twig
  templates/candidat/edit/edit.skill.html.twig
  templates/candidat/edit/hobbies.html.twig
  templates/candidat/edit/languages.html.twig
  templates/candidat/edit/sofskills.html.twig
  templates/company/editCompanyContact.html.twig
  templates/company/editCompanyDetails.html.twig
  templates/company/editCompanyNeed.html.twig
  templates/company/index.html.twig
  templates/login/index.html.twig
Labels: Reviewed, Fix

#236 added languages section in admin candidate show
  templates/admin_candidate/show.html.twig
  templates/candidat/components/_languages.html.twig
Labels: Reviewed, Fix

#234 Us16 s03 edit document
  assets/app.js
  assets/styles/forms.scss
  assets/styles/profile.scss
  composer.lock
  migrations/Version20220113172204.php
  public/uploads/.gitignore
  public/uploads/candidate/CV.pdf
  src/Controller/CandidatController.php
  src/Entity/AdditionalDocument.php
  src/Entity/Candidat.php
  src/Entity/User.php
  src/Form/CandidateDocumentType.php
  src/Form/DocumentType.php
  templates/candidat/components/_documents.html.twig
  templates/candidat/edit/edit.document.html.twig
  templates/candidat/edit/edit.skill.html.twig
Labels: Reviewed, Correction Done

#237 add users and roles in fixtures
  src/DataFixtures/CandidateFixtures.php
  src/DataFixtures/CandidateLanguageFixtures.php
  src/DataFixtures/CompanyFixtures.php
  src/DataFixtures/ExperienceFixtures.php
  src/DataFixtures/FormationFixtures.php
  src/DataFixtures/HobbyFixtures.php
  src/DataFixtures/SkillFixtures.php
  src/DataFixtures/SoftSkillFixtures.php
  src/DataFixtures/UserFixtures.php
Labels: Reviewed, Correction Done

#241 Fix company routes & navbar
  src/Controller/CompanyController.php
  templates/company/components/_companyContact.html.twig
  templates/company/components/_companyDetails.html.twig
  templates/company/components/_companyNeed.html.twig
  templates/company/components/_formCompanyContact.html.twig
  templates/company/components/_formCompanyDetails.html.twig
  templates/company/components/_formCompanyNeed.html.twig
  templates/items/_navbar.html.twig
Labels: Reviewed, Fix, Correction Done

#271 fixed the h1 not in the right div
  templates/company/index.html.twig
Labels: Reviewed, Fix

#272 Fix hide sidebar mobile
  templates/candidate/components/_SideMenuCandidate.html.twig
  templates/company/components/_SideMenuCompany.html.twig
Labels: Reviewed, Fix

#274 change style profile and edit style link
  assets/styles/profile.scss
  src/Controller/CandidateController.php
  templates/candidate/components/_complementary-questions.html.twig
  templates/candidate/components/_hobbies.html.twig
  templates/candidate/components/_languages.html.twig
  templates/candidate/components/_soft-skills.html.twig
Labels: Reviewed, Correction Done

#276 Fix flash messages company
  src/Controller/CompanyController.php
  templates/base.html.twig
Labels: Reviewed, Fix

#275 fix style form edit
  templates/candidate/edit/complementary-questions.html.twig
  templates/candidate/edit/hobbies.html.twig
  templates/candidate/edit/languages.html.twig
  templates/candidate/edit/sofskills.html.twig
Labels: Reviewed, Fix

#277 add style and security for delete company
  src/Controller/AdminCompanyController.php
  templates/admin_company/_delete_form.html.twig
  templates/admin_company/show.html.twig
Labels: Reviewed, Correction Done

#279 fixed admin link in navbar
  templates/items/_navbar.html.twig
Labels: Reviewed, Fix

#284 Us40 s04 comment candidate
  migrations/Version20220117110534.php
  src/Controller/AdminCandidateController.php
  src/Entity/Candidate.php
  src/Entity/CandidateComment.php
  src/Form/CandidateCommentType.php
  src/Repository/CandidateCommentRepository.php
  templates/admin_candidate/show.html.twig
Labels: Reviewed

#285 S04 us41 search candidate
  src/Controller/AdminCandidateController.php
  src/Form/SearchUserType.php
  src/Repository/CandidateRepository.php
  templates/admin_candidate/index.html.twig
Labels: Reviewed

#286 Us40 s04 2 view comment
  templates/candidate/index.html.twig
Labels: Reviewed

#230 S03 us07 bis intermediate form
  migrations/Version20211222092402.php
  migrations/Version20211230141213.php
  migrations/Version20220106150034.php
  src/Controller/CandidateController.php
  src/Controller/RegistrationController.php
  src/Entity/Candidate.php
  src/Entity/Company.php
  src/Entity/User.php
  src/Form/RegistrationCandidateType.php
  src/Form/RegistrationFormType.php
  templates/candidate/components/_contactDetails.html.twig
  templates/company/components/_companyDetails.html.twig
  templates/registration/register.html.twig
Labels: Reviewed, Correction Done

#290 create view and style
  assets/styles/adminCandidate.scss
  src/Controller/AdminEmployeeController.php
  src/Form/EmployeeType.php
  src/Repository/EmployeeRepository.php
  templates/admin_employee/_delete_form.html.twig
  templates/admin_employee/_form.html.twig
  templates/admin_employee/edit.html.twig
  templates/admin_employee/index.html.twig
  templates/admin_employee/new.html.twig
  templates/admin_employee/show.html.twig
Labels: Reviewed, Correction Done

#291 Fix search candidate
  src/Form/SearchUserType.php
  src/Repository/CandidateRepository.php
Labels: Reviewed

#292 US40-S04-delete-comment
  src/Controller/AdminCandidateController.php
  src/DataFixtures/UserFixtures.php
  templates/admin_candidate/_delete_form_comment.html.twig
  templates/admin_candidate/details.html.twig
  templates/admin_candidate/new.html.twig
  templates/admin_candidate/show.html.twig
Labels: Reviewed, Correction Done

#293 fix sizes
  assets/styles/services.scss
  templates/services/_company-services.html.twig
  templates/services/_particular-services.html.twig
Labels: Reviewed

#295 S04 us41 search company
  src/Controller/AdminCompanyController.php
  src/Repository/CompanyRepository.php
  templates/admin_company/index.html.twig
Labels: Reviewed

#294 US41-S04-1-add-company-comment
  migrations/Version20220118092904.php
  src/Controller/AdminCompanyController.php
  src/Entity/Company.php
  src/Entity/CompanyComment.php
  src/Form/CompanyCommentType.php
  src/Repository/CompanyCommentRepository.php
  templates/admin_company/index.html.twig
  templates/admin_company/show.html.twig
Labels: Reviewed

#296 view-comment-candidate
  templates/admin_candidate/index.html.twig
  templates/candidate/index.html.twig
Labels: Reviewed

#300 US41-S04-view-comment-company
  templates/company/index.html.twig
Labels: Reviewed

#301 US41-S04-delete-comment
  src/Controller/AdminCompanyController.php
  templates/admin_company/_delete_form_comment.html.twig
  templates/admin_company/show.html.twig
Labels: Reviewed

#302 secure and style create employee
  src/Controller/AdminEmployeeController.php
  src/Entity/Employee.php
  src/Form/EmployeeType.php
  templates/admin_employee/_form.html.twig
  templates/admin_employee/new.html.twig
Labels: Reviewed, Correction Done

#305 add style and secure route to delete member
  src/Controller/AdminEmployeeController.php
  templates/admin_employee/_delete_form.html.twig
Labels: Reviewed

#303 S04 u54 edit employee
  src/Controller/AdminEmployeeController.php
  src/Entity/Employee.php
  src/Form/EmployeeType.php
  templates/admin_employee/edit.html.twig
  templates/admin_employee/index.html.twig
Labels: Reviewed, Correction Done, Conflict

#310 fix sidebar
  templates/candidate/components/_SideMenuCandidate.html.twig
  templates/company/components/_SideMenuCompany.html.twig
Labels: Reviewed, Fix

#311 migration
  migrations/Version20220118142502.php
Labels: Reviewed

#312 cv style
  assets/styles/pdf.scss
  templates/admin_candidate/cvPdf.html.twig
Labels: Reviewed

#314 S03 us67 services details
  assets/styles/services.scss
  migrations/Version20220118105657.php
  src/Controller/ServiceController.php
  src/DataFixtures/ServiceCategoryFixtures.php
  src/DataFixtures/ServiceFixtures.php
  src/Entity/Service.php
  src/Entity/ServiceCategory.php
  src/Repository/ServiceCategoryRepository.php
  src/Repository/ServiceRepository.php
  templates/services/_company-services.html.twig
  templates/services/_particular-services.html.twig
  templates/services/index.html.twig
Labels: Reviewed

#315 add button to creat employee
  assets/styles/adminCandidate.scss
  templates/admin_employee/index.html.twig
Labels: Reviewed

#313 S04 us62 upload member photo
  composer.lock
  config/packages/vich_uploader.yaml
  migrations/Version20220118104110.php
  src/DataFixtures/EmployeeFixtures.php
  src/DataFixtures/placeholder.png
  src/Entity/Employee.php
  src/Form/EmployeeType.php
  templates/about/index.html.twig
  templates/admin_employee/index.html.twig
  yarn.lock
Labels: Reviewed, Correction Done

#316 US70-S04-progressBar
  templates/candidate/components/_SideMenuCandidate.html.twig
  templates/company/components/_SideMenuCompany.html.twig
Labels: Reviewed

#321 fix-comment
  assets/styles/variables.scss
  templates/admin_candidate/show.html.twig
  templates/admin_company/show.html.twig
  templates/candidate/index.html.twig
  templates/company/index.html.twig
Labels: Reviewed, Correction Done

#322 create view and route for profile public
  src/Controller/CandidateController.php
  templates/candidate/components/_complementary-questions.html.twig
  templates/candidate/components/_experiences.html.twig
  templates/candidate/components/_formations.html.twig
  templates/candidate/components/_hobbies.html.twig
  templates/candidate/components/_languages.html.twig
  templates/candidate/components/_skills.html.twig
  templates/candidate/components/_soft-skills.html.twig
  templates/candidate/public-profile.html.twig
Labels: Reviewed, Correction Done

#323 changed migration and uploads folder that blocked migration and fixtures
  migrations/Version20220118105657.php
  public/uploads/.gitignore
  public/uploads/employee/.gitignore
Labels: Reviewed

#325 fix order method in candidate controller
  public/uploads/candidate/.gitignore
  public/uploads/candidate/cv-61e1549d52cad894514497.pdf
  src/Controller/CandidateController.php
Labels: Reviewed

#306 add sidebar on each part of admin
  src/Controller/AdminEmployeeController.php
  templates/admin_candidate/index.html.twig
  templates/admin_candidate/show.html.twig
  templates/admin_company/index.html.twig
  templates/admin_company/show.html.twig
  templates/admin_employee/edit.html.twig
  templates/admin_employee/index.html.twig
  templates/admin_employee/new.html.twig
  templates/admin_employee/show.html.twig
  templates/base-admin.html.twig
  templates/base.html.twig
  templates/items/_sideMenuAdmin.html.twig
Labels: Reviewed, Correction Done

#332 change logo
  templates/contact/index.html.twig
Labels: Reviewed

#333 add deleted franch message for employee admin
  src/Controller/AdminEmployeeController.php
Labels: Reviewed

#328 add code ape, h1 border bottom and correct spell mistakes
  templates/admin_company/index.html.twig
  templates/admin_company/show.html.twig
Labels: Reviewed, Correction Done, Conflict

#331 add return to top
  templates/about/index.html.twig
  templates/admin_company/index.html.twig
  templates/admin_company/show.html.twig
  templates/admin_employee/index.html.twig
  templates/candidate/index.html.twig
  templates/candidate/public-profile.html.twig
  templates/company/index.html.twig
  templates/items/_footer.html.twig
  templates/items/_return.html.twig
  templates/services/index.html.twig
Labels: Reviewed, Correction Done, Conflict

#334 picture default value null
  src/Entity/Employee.php
  templates/admin_employee/_form.html.twig
  templates/admin_employee/index.html.twig
Labels: Reviewed, Correction Done, Conflict

#335 fix cards sizes
  assets/styles/services.scss
Labels: Reviewed, Correction Done, Conflict

#336 crud service and categories ok
  src/Controller/AdminServiceCategoryController.php
  src/Controller/AdminServiceController.php
  src/DataFixtures/ServiceCategoryFixtures.php
  src/Entity/Service.php
  src/Entity/ServiceCategory.php
  src/Form/ServiceCategoryType.php
  src/Form/ServiceType.php
  templates/admin_service/_delete_form.html.twig
  templates/admin_service/_form.html.twig
  templates/admin_service/edit.html.twig
  templates/admin_service/index.html.twig
  templates/admin_service/new.html.twig
  templates/admin_service_category/_delete_form.html.twig
  templates/admin_service_category/_form.html.twig
  templates/admin_service_category/edit.html.twig
  templates/admin_service_category/index.html.twig
  templates/admin_service_category/new.html.twig
  templates/services/_company-services.html.twig
  templates/services/_particular-services.html.twig
Labels: Reviewed, Correction Done

#338 added icons sidebar admin
  templates/items/_sideMenuAdmin.html.twig
Labels: Reviewed

#339 fixed sizes of cards
  templates/company/components/_companyContact.html.twig
  templates/company/components/_companyDetails.html.twig
  templates/company/components/_companyNeed.html.twig
Labels: Reviewed, Fix

#337 Fix form candidate
  assets/styles/profile.scss
  src/Controller/CandidateController.php
  src/DataFixtures/UserFixtures.php
  src/Entity/AdditionalDocument.php
  src/Entity/Candidate.php
  src/Entity/CandidateLanguage.php
  src/Entity/Experience.php
  src/Entity/Formation.php
  src/Entity/Hobby.php
  src/Entity/Sector.php
  src/Entity/Skill.php
  src/Entity/SoftSkill.php
  src/Entity/User.php
  src/Form/ExperienceType.php
  src/Form/FormationType.php
  src/Form/UserCandidateType.php
  templates/candidate/components/_complementary-questions.html.twig
  templates/candidate/components/_contactDetails.html.twig
  templates/candidate/components/_documents.html.twig
  templates/candidate/components/_experiences.html.twig
  templates/candidate/components/_formations.html.twig
  templates/candidate/components/_hobbies.html.twig
  templates/candidate/components/_languages.html.twig
  templates/candidate/components/_skills.html.twig
  templates/candidate/components/_soft-skills.html.twig
  templates/candidate/edit/complementary-questions.html.twig
  templates/candidate/edit/edit.contactDetails.html.twig
  templates/candidate/edit/edit.document.html.twig
  templates/candidate/edit/edit.experience.html.twig
  templates/candidate/edit/edit.formation.html.twig
  templates/candidate/edit/edit.skill.html.twig
  templates/candidate/edit/hobbies.html.twig
  templates/candidate/edit/languages.html.twig
  templates/candidate/edit/sofskills.html.twig
  templates/candidate/index.html.twig
Labels: Reviewed, Correction Done, Conflict

#340 create view for generales condiditions
  src/Controller/HomeController.php
  src/Form/RegistrationFormType.php
  templates/items/_footer.html.twig
  templates/legal-terms/conditions.html.twig
  templates/registration/register.html.twig
Labels: Reviewed

#341 Generate reference
  migrations/Version20220126082025.php
  src/Controller/RegistrationController.php
  src/DataFixtures/UserFixtures.php
  src/Entity/User.php
  src/Repository/UserRepository.php
  src/Services/ReferenceGenerator.php
Labels: Reviewed, Correction Done

#342 create legal notice page
  src/Controller/HomeController.php
  templates/items/_footer.html.twig
  templates/legal-terms/legal-notice.html.twig
Labels: Reviewed, Correction Done, Conflict

#343 added services to sidebar
  templates/admin_service/index.html.twig
  templates/admin_service_category/index.html.twig
  templates/items/_sideMenuAdmin.html.twig
Labels: Reviewed

#344 fixed all icons to look the same
  templates/candidate/components/_contactDetails.html.twig
  templates/candidate/components/_experiences.html.twig
  templates/candidate/components/_formations.html.twig
  templates/company/components/_companyContact.html.twig
  templates/contact/index.html.twig
  templates/items/_footer.html.twig
Labels: Reviewed

#345 fix-insert-profil-candidate
  migrations/Version20220126133956.php
  src/Entity/Candidate.php
  src/Form/ContactDetailsType.php
Labels: Reviewed

#347 title and edit on the same line
  assets/styles/companyProfile.scss
  assets/styles/profile.scss
  templates/candidate/components/_complementary-questions.html.twig
  templates/candidate/components/_contactDetails.html.twig
  templates/candidate/components/_documents.html.twig
  templates/candidate/components/_experiences.html.twig
  templates/candidate/components/_formations.html.twig
  templates/candidate/components/_hobbies.html.twig
  templates/candidate/components/_languages.html.twig
  templates/candidate/components/_skills.html.twig
  templates/candidate/components/_soft-skills.html.twig
  templates/company/components/_companyContact.html.twig
  templates/company/components/_companyDetails.html.twig
  templates/company/components/_companyNeed.html.twig
Labels: Reviewed

#346 flashes to right
  assets/styles/app.scss
  templates/base.html.twig
Labels: Reviewed

#351 added services descritption
  assets/styles/services.scss
  templates/services/_company-services.html.twig
  templates/services/_particular-services.html.twig
Labels: Reviewed

#348 add phone number for company
  migrations/Version20220126142035.php
  src/DataFixtures/CompanyFixtures.php
  src/Entity/Company.php
  src/Form/CompanyDetailsType.php
  templates/base.html.twig
  templates/company/components/_companyDetails.html.twig
  templates/company/components/_formCompanyDetails.html.twig
Labels: Reviewed

#349 view upload and admin
  assets/styles/adminCandidate.scss
  templates/admin_candidate/show.html.twig
  templates/candidate/components/_documents.html.twig
Labels: Reviewed

#353 unique reference
  src/Entity/User.php
Labels: Reviewed

#356 search by ref
  src/Controller/AdminCandidateController.php
  src/Repository/CandidateRepository.php
  templates/admin_candidate/index.html.twig
Labels: Reviewed

#359 fix-security
  src/Entity/Candidate.php
  src/Form/ContactDetailsType.php
Labels: Reviewed

#372 dev > master
  .github/workflows/deploy_prod.yml
  assets/styles/pdf.scss
  migrations/Version20220118105657.php
  migrations/Version20220126133956.php
  src/Controller/AdminCandidateController.php
  src/Controller/RegistrationController.php
  src/Entity/Candidate.php
  src/Entity/Service.php
  src/Form/ContactDetailsType.php
  src/Form/RegistrationFormType.php
  src/Form/ServiceType.php
  src/Repository/CandidateRepository.php
  templates/admin_candidate/_delete_form.html.twig
  templates/admin_candidate/_delete_form_comment.html.twig
  templates/admin_candidate/cvPdf.html.twig
  templates/admin_candidate/index.html.twig
  templates/admin_company/_delete_form.html.twig
  templates/admin_company/_delete_form_comment.html.twig
  templates/admin_employee/_delete_form.html.twig
  templates/admin_service/_delete_form.html.twig
  templates/admin_service/index.html.twig
Labels: Reviewed

#375 assert phone
  src/Entity/Contact.php
  src/Entity/User.php
  src/Form/EmployeeType.php
Labels: Reviewed

#374 fix issues with links
  assets/styles/app.scss
  templates/items/_footer.html.twig
Labels: Reviewed

#376 add messages for collectiontypes
  src/Entity/Candidate.php
Labels: Reviewed

#378 modified gender on company
  src/Form/UserCompanyType.php
Labels: Reviewed

#379 responsive contact
  templates/contact/index.html.twig
Labels: Reviewed

#381 added min width to prevent sidebar text wrapping
  assets/styles/sideMenu.scss
Labels: Reviewed

#382 corrected phone icon
  templates/company/components/_companyDetails.html.twig
Labels: Reviewed

#383 some typo fixes
  templates/about/index.html.twig
  templates/login/index.html.twig
  templates/registration/confirmation_email.html.twig
  templates/registration/register.html.twig
  templates/reset_password/check_email.html.twig
  templates/reset_password/email.html.twig
  templates/reset_password/request.html.twig
Labels: Reviewed

#373 employee form fixed
  src/Entity/Employee.php
  templates/admin_employee/edit.html.twig
Labels: Reviewed, Correction Done

#384 dev to master
  assets/styles/app.scss
  assets/styles/sideMenu.scss
  src/Entity/Candidate.php
  src/Entity/Contact.php
  src/Entity/Employee.php
  src/Entity/User.php
  src/Form/ContactDetailsType.php
  src/Form/EmployeeType.php
  src/Form/ExperienceType.php
  src/Form/FormationType.php
  src/Form/UserCompanyType.php
  templates/about/index.html.twig
  templates/admin_employee/edit.html.twig
  templates/company/components/_companyDetails.html.twig
  templates/items/_footer.html.twig
  templates/login/index.html.twig
  templates/registration/confirmation_email.html.twig
  templates/registration/register.html.twig
  templates/reset_password/check_email.html.twig
  templates/reset_password/email.html.twig
  templates/reset_password/request.html.twig
Labels: Reviewed

#385 change label form
  src/Form/EmployeeType.php
Labels: Reviewed

#386 change route for delete employee
  src/Controller/AdminCompanyController.php
Labels: Reviewed

#388 fix issues with style employee
  assets/styles/adminCandidate.scss
  templates/admin_employee/index.html.twig
Labels: Reviewed

#389 fixed presentation
  templates/about/index.html.twig
Labels: Reviewed, Fix

#409 Fix migrations
  migrations/Version20211217010327.php
  migrations/Version20211220152645.php
  migrations/Version20211221112131.php
  migrations/Version20211221142231.php
  migrations/Version20211222092402.php
  migrations/Version20211227093320.php
  migrations/Version20211227094236.php
  migrations/Version20211230141213.php
  migrations/Version20211230193451.php
  migrations/Version20211230201512.php
  migrations/Version20220103125013.php
  migrations/Version20220103151523.php
  migrations/Version20220104074012.php
  migrations/Version20220104092214.php
  migrations/Version20220104131546.php
  migrations/Version20220104163322.php
  migrations/Version20220105092117.php
  migrations/Version20220106150034.php
  migrations/Version20220111092347.php
  migrations/Version20220111102244.php
  migrations/Version20220112100131.php
  migrations/Version20220113172204.php
  migrations/Version20220117110534.php
  migrations/Version20220118092904.php
  migrations/Version20220118104110.php
  migrations/Version20220118105657.php
  migrations/Version20220118142502.php
  migrations/Version20220126082025.php
  migrations/Version20220126133956.php
  migrations/Version20220126142035.php
  migrations/Version20220130103648.php
  src/DataFixtures/CandidateFixtures.php
  src/DataFixtures/CompanyFixtures.php
  src/DataFixtures/UserFixtures.php
Labels: Reviewed

#412 Fix add help upload
  assets/app.js
  assets/styles/adminCandidate.scss
  assets/styles/app.scss
  src/Form/EmployeeType.php
  templates/base.html.twig
  templates/items/_footer.html.twig
  templates/items/_return.html.twig
Labels: Reviewed

#414 added a placeholder
  src/Form/CandidateLanguageType.php
Labels: Reviewed

#415 modified test users
  src/DataFixtures/CandidateFixtures.php
  src/DataFixtures/CandidateLanguageFixtures.php
  src/DataFixtures/CompanyFixtures.php
  src/DataFixtures/ExperienceFixtures.php
  src/DataFixtures/FormationFixtures.php
  src/DataFixtures/HobbyFixtures.php
  src/DataFixtures/SkillFixtures.php
  src/DataFixtures/SoftSkillFixtures.php
  src/DataFixtures/UserFixtures.php
Labels: Reviewed

#413 display correctly the user gender when he modifie his information
  src/Form/RegistrationFormType.php
Labels: Reviewed

#416 added a error 403 page
  composer.lock
  symfony.lock
  templates/bundles/TwigBundle/Exception/error403.html.twig
Labels: Reviewed

#417 fix-comment
  assets/styles/companyProfile.scss
  assets/styles/profile.scss
  src/DataFixtures/CompanyFixtures.php
  templates/admin_candidate/show.html.twig
  templates/admin_company/show.html.twig
  templates/candidate/index.html.twig
  templates/company/index.html.twig
Labels: Reviewed

#418 added customer text
  assets/styles/about.scss
  templates/about/index.html.twig
Labels: Reviewed

#419 Fix redirection services
  src/Controller/AdminServiceCategoryController.php
  templates/admin_service/index.html.twig
  templates/admin_service_category/_form.html.twig
  templates/admin_service_category/index.html.twig
  templates/admin_service_category/new.html.twig
Labels: Reviewed

#420 services are no more collapsed by default
  templates/services/_company-services.html.twig
  templates/services/_particular-services.html.twig
Labels: Reviewed
